#!/usr/bin/env ruby

require 'etc'

work_email = 'giams@di.fm'

if Dir.pwd =~ %r|^/Users/#{Etc.getlogin}/src/work/| &&
    `git config --get user.email`.strip != work_email
  %x(git config --add user.email #{work_email})
end
